package com.wss_mqtt_prefab.security.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wss_mqtt_prefab.security.Security;
import com.wss_mqtt_prefab.security.model.STSCredentials;

/**
 * Controller object for domain model class {@link Security}.
 * @see Security
 */
@RestController
@Api(value = "SecurityController", description = "controller class for java service execution")
@RequestMapping("/security")
public class SecurityController {

    @Autowired
    private Security security;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @GetMapping(value = "/sTssessionToken")
    public STSCredentials getSTSSessionToken() {
        return security.getSTSSessionToken();
    }
}

